service: hotnews

provider:
  name: aws
  runtime: nodejs12.x

functions:
  headlines:
    handler: dist/headlines.send
    events:
      - schedule: cron(0 7 * * ? *)
  tech:
    handler: dist/tech.send
    events:
      - schedule: cron(0 8 * * ? *)
      - schedule: cron(30 13 * * ? *)
  sportuk:
    handler: dist/sportuk.send
    events:
      - schedule: cron(30 8 * * ? *)
      - schedule: cron(30 17 * * ? *)
  business:
    handler: dist/business.send
    events:
      - schedule: cron(30 7 * * ? *)
plugins:
  - serverless-offline